apiVersion: v1
kind: Namespace
metadata:
  name: localstack
  labels:
    kubernetes.io/metadata.name: localstack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:2.0.0
        ports:
        - containerPort: 4566
        env:
        - name: SERVICES
          value: rds,s3,iam
        - name: DEBUG
          value: "1"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: localstack
spec:
  ports:
  - port: 4566
    targetPort: 4566
  selector:
    app: localstack
